### Request 1
GET http://localhost:3000/finances


### Request 2
POST http://localhost:3000/finances/new
Content-Type: application/json

{
  "income": "4000",
  "expenseBudget": "1500",
  "savings": "150",
  "investments": "100",
  "timestamp": "3/8/2023"
}

### Request 3
POST http://localhost:3000/sign/up
Content-Type: application/json

{
  "email": "newemail4@gmail.com",
  "password": "helloworld"
}

### Request 4
POST http://localhost:3000/sign/in
Content-Type: application/json

{
  "email": "newemail3@gmail.com",
  "password": "helloworld"
}

### Request 5
GET http://localhost:3000/finances/getcookie

// file for testing dummy DB requests in real time within VSCode